### ISSUE TITLE
Take out config for image upload in endpoint.go as an environment variables

### ISSUE THREAD

**Issue by KKhanda** [KazanExpress/louis#17]
<img width="418" alt="screen shot 2018-08-23 at 15 36 04" src="https://user-images.githubusercontent.com/14187000/44525740-a1afa100-a6ea-11e8-86fc-ab0e2546179d.png">
These constants could be extracted as an environment variables

**Comment by alikhil** [comment]
By the way, `HighCompressionQuality` and `LowCompressionQuality` not in use anymore
