### ISSUE TITLE
Benchmark parallel and sequential image proccesing 

### ISSUE THREAD

**Issue by alikhil** [KazanExpress/louis#32]
[Post in stackoverflow](https://stackoverflow.com/questions/15771232/why-is-time-sleep-required-to-run-certain-goroutines
) claims that `The goroutine scheduler is not preemptive. Your goroutines have to give up control before another goroutine will run` it can mean that parallel image processing takes more time.

[read more](https://rakyll.org/scheduler/)

also we may play with `GONUMPROCS`

**Comment by alikhil** [comment]
> Go uses compiler-inserted cooperative preemption points
[source](https://github.com/golang/go/issues/24543)
WOW!

**Comment by alikhil** [comment]
> Apparently, the Go codebase is littered with Gosched calls, so whenever you call time.Sleep or fmt.Printf, Gosched will be called for you

[source](https://container-solutions.com/surprise-golang-thread-scheduling/)

Ahaa!

**Comment by alikhil** [comment]
I made a small benchmark, the hypothesis is rejected. It makes sense because among processing image there is image upload which possibly blocks CPU and makes parallel computing more effective

**Comment by Azareal** [comment]
All function calls are scheduler points, I believe.

It's probably only a problem, if you have a tight loop which runs for a really long time with no functions being called.
