### ISSUE TITLE
Add progressive jpeg support

### ISSUE THREAD

**Issue by alikhil** [KazanExpress/louis#38]
Transforming pictures as progressive will increase page load speed.

libvips [supports](https://github.com/kjell/libvips/commit/0bfb23eca86e221dc8d5cfd881c3dfba2d5d380b) saving jpeg as progressive. 

Todo:
- [ ] Implement asyncronous progressive save
- [ ] Reformat old pictures as progressive

**Comment by Raiondesu** [comment]
@kaskar2008 should've created this!

Uh.
